name: 'Rulebix Publish Action'
description: 'Publish rules to Rulebix Registry using OIDC'
author: 'Rulebix'

inputs:
  api_url:
    description: 'The Rulebix Registry API URL'
    required: false
    default: 'https://api.rulebix.workers.dev'
  retries:
    description: 'Number of retries on network failure'
    required: false
    default: 3

runs:
  using: "composite"
  steps:
    - name: Get OIDC Token
      id: get_token
      shell: bash
      run: |
        RESPONSE=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=rulebix")
        
        ID_TOKEN=$(echo "$RESPONSE" | jq -r '.value')
        
        if [ -z "$ID_TOKEN" ] || [ "$ID_TOKEN" == "null" ]; then
          echo "::error::Failed to retrieve OIDC token. Ensure 'permissions: id-token: write' is set."
          exit 1
        fi
        
        echo "::add-mask::$ID_TOKEN"
        echo "token=$ID_TOKEN" >> "$GITHUB_OUTPUT"

    - name: Notify Rulebix Registry (JSON with jq + retries)
      shell: bash
      env:
        REGISTRY_API: "${{ inputs.api_url }}"
        REPO: "${{ github.repository }}"
        RAW_VERSION: "${{ github.event.release.tag_name }}"
        TOKEN: "${{ steps.get_token.outputs.token }}"
        MAX_RETRIES: "${{ inputs.retries }}"
      run: |
        # Build JSON payload safely using jq
        PAYLOAD=$(jq -n --arg repo "$REPO" --arg version "$RAW_VERSION" \
          '{repo: $repo, version: $version}')

        attempt=1
        while [ $attempt -le $MAX_RETRIES ]; do
          echo "Attempt $attempt: Publishing $RAW_VERSION to Rulebix Registry..."
          
          HTTP_RESPONSE=$(curl -s -o response.txt -w "%{http_code}" -X POST "$REGISTRY_API/publish" \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD")
          
          if [[ "$HTTP_RESPONSE" -ge 200 && "$HTTP_RESPONSE" -lt 300 ]]; then
            echo "✅ Successfully published $RAW_VERSION to Rulebix Registry"
            break
          else
            echo "::warning::Attempt $attempt failed. HTTP code: $HTTP_RESPONSE"
            cat response.txt
            if [ $attempt -eq $MAX_RETRIES ]; then
              echo "::error::Failed to publish after $MAX_RETRIES attempts."
              exit 1
            fi
            attempt=$((attempt + 1))
            sleep 2
          fi
        done
