name: Rulebix Publish Action
description: Validate and publish Rulebix rules to Registry using OIDC
author: Rulebix

inputs:
  api_url:
    description: Rulebix Registry API URL
    required: false
    default: https://nuxt.ineceper.my.id/api/v1/publish
  retries:
    description: Number of retries on network failure
    required: false
    default: 3

runs:
  using: composite
  steps:
    - name: Request OIDC token
      shell: bash
      run: |
        set -e

        if [ -z "$ACTIONS_ID_TOKEN_REQUEST_TOKEN" ] || [ -z "$ACTIONS_ID_TOKEN_REQUEST_URL" ]; then
          echo "::error::OIDC token request environment variables not available. Ensure 'id-token: write' permission is set in workflow."
          exit 1
        fi

        OIDC_TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=rulebix-registry" | jq -r '.value')

        if [ -z "$OIDC_TOKEN" ] || [ "$OIDC_TOKEN" = "null" ]; then
          echo "::error::Failed to obtain OIDC token from GitHub. Ensure 'id-token: write' permission is set in workflow."
          exit 1
        fi

        echo "OIDC_TOKEN=$OIDC_TOKEN" >> $GITHUB_ENV
        echo "OIDC token acquired successfully"

    - name: Run Publish Script
      shell: bash
      env:
        REGISTRY_API: ${{ inputs.api_url }}
        GITHUB_TOKEN: ${{ github.token }} # Optional, if needed later
      run: |
        # Ensure node is available (usually is on standard runners)
        if ! command -v node &> /dev/null; then
            echo "::error::Node.js is required but not found."
            exit 1
        fi

        node ${{ github.action_path }}/scripts/publish.js
